const STORAGE='vboard-sprint6';
const court=document.getElementById('court'), zonesEl=document.getElementById('zones'), tokensEl=document.getElementById('tokens'), ballEl=document.getElementById('ball');
const defaultPlayers=[
 {id:'h1',team:'home',no:'1',nick:'リオ',grade:'4年',height:'155cm',gender:'女',pos:'S',x:50,y:82,zone:{w:19,h:19,r:0}},
 {id:'h2',team:'home',no:'2',nick:'ミオ',grade:'4年',height:'160cm',gender:'女',pos:'MB',x:50,y:74,zone:{w:19,h:19,r:0}},
 {id:'h3',team:'home',no:'3',nick:'ユイ',grade:'4年',height:'158cm',gender:'女',pos:'OH',x:22,y:74,zone:{w:19,h:19,r:0}},
 {id:'h4',team:'home',no:'5',nick:'アオ',grade:'4年',height:'157cm',gender:'女',pos:'MB',x:22,y:88,zone:{w:19,h:19,r:0}},
 {id:'h5',team:'home',no:'6',nick:'ハル',grade:'4年',height:'156cm',gender:'女',pos:'OH',x:78,y:88,zone:{w:19,h:19,r:0}},
 {id:'h6',team:'home',no:'7',nick:'ナナ',grade:'4年',height:'159cm',gender:'女',pos:'OP',x:78,y:74,zone:{w:19,h:19,r:0}},
 {id:'o1',team:'opp',no:'OH',nick:'OH',pos:'OH',x:22,y:25,zone:{w:18,h:18,r:0}},
 {id:'o2',team:'opp',no:'MB',nick:'MB',pos:'MB',x:50,y:25,zone:{w:18,h:18,r:0}},
 {id:'o3',team:'opp',no:'OP',nick:'OP',pos:'OP',x:78,y:25,zone:{w:18,h:18,r:0}},
 {id:'o4',team:'opp',no:'S',nick:'S',pos:'S',x:22,y:39,zone:{w:18,h:18,r:0}},
 {id:'o5',team:'opp',no:'L',nick:'L',pos:'L',x:50,y:39,zone:{w:18,h:18,r:0}},
 {id:'o6',team:'opp',no:'OH',nick:'OH',pos:'OH',x:78,y:39,zone:{w:18,h:18,r:0}}
];
let state=load()||{team:'A',sceneId:'s1',scenes:[{id:'s1',name:'相手レフト',players:structuredClone(defaultPlayers),ball:{x:50,y:56,h:45}}],teams:['A']};
let selectedId='h1', dragging=null, pressTimer=null;
function load(){try{return JSON.parse(localStorage.getItem(STORAGE))}catch{return null}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function scene(){return state.scenes.find(s=>s.id===state.sceneId)||state.scenes[0]}
function pctX(p){return p.x/100*court.clientWidth} function pctY(p){return p.y/100*court.clientHeight}
function render(){document.getElementById('sceneName').textContent=scene().name;zonesEl.innerHTML='';tokensEl.innerHTML='';
 scene().players.forEach(p=>{renderZone(p);renderToken(p)}); renderBall(); renderLists(); save();}
function renderZone(p){const z=document.createElement('div');z.className=`zone ${p.team==='opp'?'opp':''} ${p.id===selectedId?'selected':''}`;z.dataset.id=p.id; const w=p.zone.w/100*court.clientWidth,h=p.zone.h/100*court.clientWidth; z.style.width=w+'px';z.style.height=h+'px';z.style.left=(pctX(p)-w/2)+'px';z.style.top=(pctY(p)-h/2)+'px';z.style.transform=`rotate(${p.zone.r}deg)`;zonesEl.appendChild(z);
 if(p.id===selectedId){['r','b','s','rot'].forEach(cls=>{const hnd=document.createElement('div');hnd.className='handle '+cls;hnd.dataset.kind=cls;z.appendChild(hnd);hnd.addEventListener('pointerdown',startHandle)});}}
function renderToken(p){const t=document.createElement('div');t.className=`token ${p.team==='opp'?'opp':''} ${p.id===selectedId?'selected':''}`;t.dataset.id=p.id;t.style.left=(pctX(p)-28)+'px';t.style.top=(pctY(p)-28)+'px';t.innerHTML=`<span class="main">${p.team==='opp'?p.no:p.no}</span><span class="sub">${p.team==='opp'?p.pos:p.nick}</span>`;tokensEl.appendChild(t);t.addEventListener('pointerdown',startDrag);t.addEventListener('click',()=>{selectedId=p.id;render()});}
function renderBall(){const b=scene().ball;ballEl.style.left=(pctX(b)-23)+'px';ballEl.style.top=(pctY(b)-23-b.h/6)+'px';ballEl.style.boxShadow=`0 ${16+b.h/4}px ${12+b.h/5}px rgba(0,0,0,.28)`;ballEl.onpointerdown=e=>{dragging={type:'ball',id:'ball'};ballEl.setPointerCapture(e.pointerId)}}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))} function posFromEvent(e){const r=court.getBoundingClientRect();return {x:clamp((e.clientX-r.left)/r.width*100,0,100),y:clamp((e.clientY-r.top)/r.height*100,0,100)}}
function startDrag(e){e.preventDefault();const id=e.currentTarget.dataset.id;selectedId=id;const p=scene().players.find(x=>x.id===id);dragging={type:'player',id,dx:posFromEvent(e).x-p.x,dy:posFromEvent(e).y-p.y};e.currentTarget.setPointerCapture(e.pointerId);pressTimer=setTimeout(()=>openEdit(id),550);render();}
function startHandle(e){e.preventDefault();e.stopPropagation();const p=scene().players.find(x=>x.id===selectedId);dragging={type:'handle',kind:e.currentTarget.dataset.kind,start:{x:e.clientX,y:e.clientY,w:p.zone.w,h:p.zone.h,r:p.zone.r}};e.currentTarget.setPointerCapture(e.pointerId)}
window.addEventListener('pointermove',e=>{if(!dragging)return; if(pressTimer){clearTimeout(pressTimer);pressTimer=null} const s=scene(); if(dragging.type==='player'){const p=s.players.find(x=>x.id===dragging.id);const pos=posFromEvent(e);p.x=clamp(pos.x-dragging.dx,3,97);p.y=clamp(pos.y-dragging.dy,3,97);render()} if(dragging.type==='ball'){const pos=posFromEvent(e);s.ball.x=pos.x;s.ball.y=pos.y;renderBall();save()} if(dragging.type==='handle'){const p=s.players.find(x=>x.id===selectedId);const dx=(e.clientX-dragging.start.x)/court.clientWidth*100,dy=(e.clientY-dragging.start.y)/court.clientWidth*100; if(dragging.kind==='r')p.zone.w=clamp(dragging.start.w+dx*2,10,70); if(dragging.kind==='b')p.zone.h=clamp(dragging.start.h+dy*2,10,70); if(dragging.kind==='s'){const d=Math.max(dx,dy)*2;p.zone.w=clamp(dragging.start.w+d,10,70);p.zone.h=clamp(dragging.start.h+d,10,70)} if(dragging.kind==='rot')p.zone.r=dragging.start.r+(e.clientX-dragging.start.x); render();}});
window.addEventListener('pointerup',()=>{dragging=null;if(pressTimer){clearTimeout(pressTimer);pressTimer=null}});
function renderLists(){const sc=document.getElementById('sceneList'); if(sc){sc.innerHTML='';state.scenes.forEach(s=>{const b=document.createElement('button');b.textContent=(s.id===state.sceneId?'✓ ':'')+s.name;b.onclick=()=>{state.sceneId=s.id;closeSheets();render()};sc.appendChild(b)})}
 const pl=document.getElementById('playerList'); if(pl){pl.innerHTML='';scene().players.filter(p=>p.team==='home').forEach(p=>{const row=document.createElement('div');row.className='player-row';row.innerHTML=`<div class="badge">${p.no}</div><div class="meta"><div class="name">${p.nick}</div><div class="detail">${p.pos||'-'} / ${p.grade||'-'} / ${p.height||'-'}</div></div><span>›</span>`;row.onclick=()=>openEdit(p.id);pl.appendChild(row)})}
 const tl=document.getElementById('teamList'); if(tl){tl.innerHTML='';state.teams.forEach(t=>{const b=document.createElement('button');b.textContent=(t===state.team?'✓ ':'')+t+'チーム';tl.appendChild(b)})}}
function openSheet(id){document.getElementById(id).classList.add('open')} function closeSheets(){document.querySelectorAll('.sheet').forEach(s=>s.classList.remove('open'))}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).classList.remove('open'));
document.getElementById('sceneBtn').onclick=()=>openSheet('sceneSheet');document.getElementById('playersBtn').onclick=()=>openSheet('playerSheet');document.getElementById('teamBtn').onclick=()=>openSheet('teamSheet');
document.getElementById('newSceneBtn').onclick=()=>{const name=prompt('シーン名','新しいシーン');if(!name)return;const base=structuredClone(scene());base.id='s'+Date.now();base.name=name;state.scenes.push(base);state.sceneId=base.id;render();};document.getElementById('sceneAddBtn').onclick=()=>document.getElementById('newSceneBtn').click();
document.getElementById('resetBtn').onclick=()=>{if(confirm('このシーンを初期配置に戻しますか？')){scene().players=structuredClone(defaultPlayers);scene().ball={x:50,y:56,h:45};render()}};
document.getElementById('rangeBtn').onclick=()=>{const p=scene().players.find(x=>x.id===selectedId);p.zone={w:19,h:19,r:0};render()};document.getElementById('ballBtn').onclick=()=>{selectedId=null;scene().ball={x:50,y:56,h:45};render()};document.getElementById('undoBtn').onclick=()=>alert('UNDOは次回実装予定です');
function openEdit(id){selectedId=id;const p=scene().players.find(x=>x.id===id);document.getElementById('editTitle').textContent=p.team==='opp'?'相手選手編集':'選手編集';document.getElementById('editNick').value=p.nick||'';document.getElementById('editNo').value=p.no||'';document.getElementById('editGrade').value=p.grade||'';document.getElementById('editHeight').value=p.height||'';document.getElementById('editGender').value=p.gender||'未設定';document.getElementById('editPos').value=p.pos||'';document.getElementById('editPersonality').value=p.personality||'';document.getElementById('editCoach').value=p.coach||'';document.getElementById('editBackdrop').classList.add('open');document.getElementById('editSheet').classList.add('open');render()}
function closeEdit(){document.getElementById('editBackdrop').classList.remove('open');document.getElementById('editSheet').classList.remove('open')}document.getElementById('cancelEdit').onclick=closeEdit;document.getElementById('editBackdrop').onclick=closeEdit;document.getElementById('saveEdit').onclick=()=>{const p=scene().players.find(x=>x.id===selectedId);p.nick=document.getElementById('editNick').value;p.no=document.getElementById('editNo').value;p.grade=document.getElementById('editGrade').value;p.height=document.getElementById('editHeight').value;p.gender=document.getElementById('editGender').value;p.pos=document.getElementById('editPos').value;p.personality=document.getElementById('editPersonality').value;p.coach=document.getElementById('editCoach').value;closeEdit();render()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('publicTab').classList.toggle('hidden',b.dataset.tab!=='public');document.getElementById('coachTab').classList.toggle('hidden',b.dataset.tab!=='coach')});
let startX=0,startY=0;window.addEventListener('touchstart',e=>{startX=e.touches[0].clientX;startY=e.touches[0].clientY},{passive:true});window.addEventListener('touchend',e=>{if(dragging)return;const dx=(e.changedTouches[0].clientX-startX),dy=(e.changedTouches[0].clientY-startY);if(Math.abs(dx)>120&&Math.abs(dx)>Math.abs(dy)*1.5){if(startX>window.innerWidth-32&&dx<0)openSheet('playerSheet'); if(startX<32&&dx>0)openSheet('teamSheet')} if(startY<90&&dy>110&&Math.abs(dx)<80)openSheet('sceneSheet')},{passive:true});
render();
