const POS=[
  {key:'LF',jp:'レフト',x:.24,y:.66},{key:'S',jp:'セッター',x:.50,y:.66},{key:'RF',jp:'ライト',x:.76,y:.66},
  {key:'BL',jp:'Bレフト',x:.24,y:.82},{key:'C',jp:'センター',x:.50,y:.82},{key:'BR',jp:'Bライト',x:.76,y:.82}
];
const OPP=[
  {key:'LF',jp:'レフト',x:.24,y:.18},{key:'S',jp:'セッター',x:.50,y:.18},{key:'RF',jp:'ライト',x:.76,y:.18},
  {key:'BL',jp:'Bレフト',x:.24,y:.34},{key:'C',jp:'センター',x:.50,y:.34},{key:'BR',jp:'Bライト',x:.76,y:.34}
];
const H=['top','right','bottom','left','scale','rot'];
const initial=()=>({
 teams:[{id:'A',name:'A'}],team:'A',scene:'サーブレシーブ',ballType:'molten',
 scenes:{'A::サーブレシーブ':{players:POS.map((p,i)=>({id:'p'+i,team:'my',pos:p.key,posJp:p.jp,name:'',grade:'',height:'',age:'',x:p.x,y:p.y,rx:.105,ry:.105,rot:0})).concat(OPP.map((p,i)=>({id:'o'+i,team:'opp',pos:p.key,posJp:p.jp,name:'',x:p.x,y:p.y,rx:.095,ry:.095,rot:0}))),ball:{x:.5,y:.5,h:45}}}
});
let state=load();let selected='p1',mode='select',subPick=null,drag=null,longTimer=null;const $=q=>document.querySelector(q), app=$('#app');
function load(){try{return JSON.parse(localStorage.vboard12)||initial()}catch(e){return initial()}}
function save(){localStorage.vboard12=JSON.stringify(state)}
const key=()=>`${state.team}::${state.scene}`; const cur=()=>state.scenes[key()]||(state.scenes[key()]=JSON.parse(JSON.stringify(state.scenes['A::サーブレシーブ'])));
function jp(key){return ({LF:'レフト',S:'セッター',RF:'ライト',BL:'Bレフト',C:'センター',BR:'Bライト'}[key]||key)}
function render(){let c=cur();app.innerHTML=`<div class="app"><div class="top"><button class="team" id="teamBtn">${state.team}</button><button class="scene" id="sceneBtn">${state.scene} ▼</button><button class="playersBtn" id="playersBtn">選手</button></div><div class="stage"><button class="sideHandle leftHandle" id="teamsHandle">‹</button><button class="sideHandle rightHandle" id="playersHandle">›</button><div class="courtWrap"><div class="court" id="court"><div class="half oppHalf"><span class="label oppLabel">相手コート</span></div><div class="half myHalf"></div><div class="attack attackTop"></div><div class="attack attackBottom"></div><div class="centerLine"></div><div class="net"></div></div></div><div class="bottomBar"><button class="barBtn" id="undo"><b>↶</b>UNDO</button><button class="barBtn" id="rangeMode"><b>◌</b>範囲</button><button class="barBtn" id="subMode"><b>⇄</b>交代</button><button class="barBtn" id="sceneAdd"><b>＋</b>シーン</button><button class="barBtn" id="reset"><b>⌫</b>リセット</button></div></div><div class="drawer right" id="playerDrawer"><button class="close" data-close>×</button><h2>選手一覧</h2><div class="list">${c.players.filter(p=>p.team==='my').map((p,i)=>`<div class="row" data-edit="${p.id}"><span class="num">${i+1}</span><div><b>${p.name||jp(p.pos)}</b><small>${jp(p.pos)} ${p.grade?'/ '+p.grade+'年':''} ${p.height?'/ '+p.height+'cm':''}</small></div><span>›</span></div>`).join('')}<button class="add" id="addPlayer">＋ 選手追加</button></div></div><div class="drawer left" id="teamDrawer"><button class="close" data-close>×</button><h2>チーム</h2><div class="list">${state.teams.map(t=>`<div class="row" data-team="${t.id}"><span class="num">${t.id}</span><div><b>${t.name}</b><small>タップで切替</small></div><span>›</span></div>`).join('')}<button class="add" id="addTeam">＋ チーム追加</button></div></div><div class="sheet" id="sheet"></div></div>`;
 const court=$('#court'); c.players.forEach(p=>{addRange(court,p);addPlayer(court,p)}); addBall(court,c.ball); addHandles(); bind();}
function addRange(court,p){const d=document.createElement('div');d.className='range '+(p.id===selected?'selected':'');d.dataset.range=p.id;Object.assign(d.style,{left:p.x*100+'%',top:p.y*100+'%',width:p.rx*200+'%',height:p.ry*100+'%'});d.style.setProperty('--rot',p.rot+'deg');court.appendChild(d)}
function addPlayer(court,p){const el=document.createElement('div');el.className='player '+(p.team==='opp'?'opp ':'')+(p.id===selected?'selected':'');el.dataset.id=p.id;let name=p.team==='opp'?jp(p.pos):(p.name||'');let pos=p.team==='opp'?'':jp(p.pos); if(!name && p.team==='my'){name=jp(p.pos);pos=''}
 el.innerHTML=`<div class="pText"><span class="pName ${p.team==='opp'?'onlyPos':''}">${name}</span>${pos?`<span class="pPos">${pos}</span>`:''}</div>`;Object.assign(el.style,{left:p.x*100+'%',top:p.y*100+'%'});court.appendChild(el)}
function addBall(court,b){const el=document.createElement('div');el.id='ball';el.className='ball '+state.ballType;el.dataset.brand=state.ballType==='molten'?'molten':'MIKASA';Object.assign(el.style,{left:b.x*100+'%',top:b.y*100+'%',width:(42+b.h/10)+'px',height:(42+b.h/10)+'px'});court.appendChild(el)}
function addHandles(){const p=cur().players.find(x=>x.id===selected); if(!p) return; const court=$('#court'), r=court.getBoundingClientRect(); const cx=p.x*r.width,cy=p.y*r.height, rx=p.rx*r.width, ry=p.ry*r.height; const pts={top:[cx,cy-ry],right:[cx+rx,cy],bottom:[cx,cy+ry],left:[cx-rx,cy],scale:[cx+rx*.72,cy+ry*.72],rot:[cx+rx*.9,cy-ry*.9]}; H.forEach(h=>{let d=document.createElement('div');d.className='handleDot '+(h==='rot'?'rotDot':'');d.dataset.handle=h;d.style.left=pts[h][0]+'px';d.style.top=pts[h][1]+'px';court.appendChild(d)})}
function bind(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeDrawers); $('#playersBtn').onclick=()=>openDrawer('right'); $('#playersHandle').onclick=()=>openDrawer('right'); $('#teamsHandle').onclick=()=>openDrawer('left'); $('#teamBtn').onclick=()=>openDrawer('left'); $('#sceneBtn').onclick=sceneMenu; $('#sceneAdd').onclick=()=>{let n=prompt('シーン名','新しいシーン'); if(n){state.scene=n; cur(); save(); render()}}; $('#reset').onclick=()=>{if(confirm('現在のシーンを初期化しますか？')){delete state.scenes[key()];cur();save();render()}}; $('#subMode').onclick=()=>{mode='sub';subPick=null;toast('交代する2人を順にタップ')}; $('#rangeMode').onclick=()=>toast('白い点で範囲を調整できます'); $('#addPlayer').onclick=()=>addNewPlayer(); $('#addTeam').onclick=()=>addNewTeam(); document.querySelectorAll('[data-edit]').forEach(r=>r.onclick=()=>editPlayer(r.dataset.edit)); document.querySelectorAll('[data-team]').forEach(r=>r.onclick=()=>{state.team=r.dataset.team;cur();save();render()}); bindCourt();}
function bindCourt(){const court=$('#court'); court.querySelectorAll('.player').forEach(el=>{el.addEventListener('pointerdown',ev=>{ev.preventDefault();const id=el.dataset.id; selected=id; const p=cur().players.find(x=>x.id===id); longTimer=setTimeout(()=>editPlayer(id),650); drag={type:'player',id,dx:0,dy:0}; el.setPointerCapture(ev.pointerId); render()})}); court.querySelectorAll('.handleDot').forEach(el=>{el.addEventListener('pointerdown',ev=>{ev.preventDefault();drag={type:'handle',h:el.dataset.handle};el.setPointerCapture(ev.pointerId)})}); $('#ball').addEventListener('pointerdown',ev=>{ev.preventDefault();drag={type:'ball'};$('#ball').setPointerCapture(ev.pointerId)}); court.addEventListener('pointermove',move); court.addEventListener('pointerup',up); court.addEventListener('pointercancel',up)}
function posFrom(ev){const r=$('#court').getBoundingClientRect();return {x:Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(ev.clientY-r.top)/r.height)),r}}
function move(ev){if(!drag)return;clearTimeout(longTimer);let c=cur(), pt=posFrom(ev); if(drag.type==='player'){let p=c.players.find(x=>x.id===drag.id);p.x=pt.x;p.y=pt.y;save();quickUpdate()} if(drag.type==='ball'){c.ball.x=pt.x;c.ball.y=pt.y;save();quickUpdate()} if(drag.type==='handle'){let p=c.players.find(x=>x.id===selected);let dx=pt.x-p.x, dy=pt.y-p.y; if(drag.h==='right'||drag.h==='left')p.rx=Math.max(.07,Math.abs(dx)); if(drag.h==='top'||drag.h==='bottom')p.ry=Math.max(.07,Math.abs(dy)); if(drag.h==='scale'){let v=Math.max(.08,Math.hypot(dx,dy));p.rx=v;p.ry=v} if(drag.h==='rot')p.rot=Math.atan2(dy,dx)*180/Math.PI; save();quickUpdate()}}
function up(ev){if(drag&&drag.type==='player'&&mode==='sub'){if(!subPick)subPick=drag.id;else if(subPick!==drag.id){let c=cur(),a=c.players.find(p=>p.id===subPick),b=c.players.find(p=>p.id===drag.id);[a.x,b.x]=[b.x,a.x];[a.y,b.y]=[b.y,a.y];mode='select';subPick=null;save();render();return}} drag=null;clearTimeout(longTimer)}
function quickUpdate(){render()}
function editPlayer(id){const p=cur().players.find(x=>x.id===id); if(!p||p.team==='opp')return; const grades=[1,2,3,4,5,6].map(n=>`<option ${p.grade==n?'selected':''}>${n}</option>`).join(''); const heights=Array.from({length:81},(_,i)=>100+i).map(n=>`<option ${p.height==n?'selected':''}>${n}</option>`).join(''); const ages=Array.from({length:13},(_,i)=>6+i).map(n=>`<option ${p.age==n?'selected':''}>${n}</option>`).join(''); const positions=POS.map(x=>`<option value="${x.key}" ${p.pos===x.key?'selected':''}>${x.jp}</option>`).join(''); const s=$('#sheet');s.innerHTML=`<h3>選手情報編集</h3><div class="grid"><div class="field"><label>ニックネーム</label><input id="eName" value="${p.name||''}" placeholder="未入力OK"></div><div class="field"><label>ポジション</label><select id="ePos">${positions}</select></div><div class="field"><label>学年</label><select id="eGrade"><option></option>${grades}</select></div><div class="field"><label>身長</label><select id="eHeight"><option></option>${heights}</select></div><div class="field"><label>年齢</label><select id="eAge"><option></option>${ages}</select></div><div class="field"><label>ボール</label><select id="eBall"><option value="molten" ${state.ballType==='molten'?'selected':''}>モルテン風</option><option value="mikasa" ${state.ballType==='mikasa'?'selected':''}>ミカサ風</option></select></div></div><button class="save" id="savePlayer">保存</button>`;s.classList.add('open');$('#savePlayer').onclick=()=>{p.name=$('#eName').value.trim();p.pos=$('#ePos').value;p.posJp=jp(p.pos);p.grade=$('#eGrade').value;p.height=$('#eHeight').value;p.age=$('#eAge').value;state.ballType=$('#eBall').value;save();s.classList.remove('open');render()}}
function addNewPlayer(){let c=cur();let idx=c.players.filter(p=>p.team==='my').length;let base=POS[idx%6];c.players.push({id:'p'+Date.now(),team:'my',pos:base.key,posJp:base.jp,name:'',grade:'',height:'',age:'',x:base.x,y:base.y,rx:.105,ry:.105,rot:0});save();render()}
function addNewTeam(){let name=prompt('チーム名','新チーム'); if(!name)return; let id=String.fromCharCode(65+state.teams.length);state.teams.push({id,name});state.team=id;cur();save();render()}
function openDrawer(side){closeDrawers();$('#'+(side==='right'?'playerDrawer':'teamDrawer')).classList.add('open')}function closeDrawers(){document.querySelectorAll('.drawer').forEach(d=>d.classList.remove('open'))}
function sceneMenu(){let n=prompt('シーン名を入力 / 変更',state.scene); if(n){state.scene=n;cur();save();render()}}
function toast(t){let d=document.createElement('div');d.textContent=t;Object.assign(d.style,{position:'absolute',top:'88px',left:'50%',transform:'translateX(-50%)',background:'#000c',color:'#fff',padding:'10px 16px',borderRadius:'22px',zIndex:99,fontWeight:900});document.body.appendChild(d);setTimeout(()=>d.remove(),1500)}
render();
