const STORAGE='vboard-sprint8';
const court=document.getElementById('court'), zonesEl=document.getElementById('zones'), tokensEl=document.getElementById('tokens'), ballEl=document.getElementById('ball');
const baseHome=[
 {id:'h1',team:'home',no:'1',nick:'リオ',grade:'4年',height:'155cm',gender:'女',pos:'S',x:50,y:84,zone:{w:18,h:18,r:0}},
 {id:'h2',team:'home',no:'2',nick:'ミオ',grade:'4年',height:'160cm',gender:'女',pos:'MB',x:50,y:74,zone:{w:18,h:18,r:0}},
 {id:'h3',team:'home',no:'3',nick:'ユイ',grade:'4年',height:'158cm',gender:'女',pos:'OH',x:22,y:74,zone:{w:18,h:18,r:0}},
 {id:'h4',team:'home',no:'4',nick:'アオ',grade:'4年',height:'157cm',gender:'女',pos:'MB',x:22,y:88,zone:{w:18,h:18,r:0}},
 {id:'h5',team:'home',no:'5',nick:'ハル',grade:'4年',height:'156cm',gender:'女',pos:'OH',x:78,y:88,zone:{w:18,h:18,r:0}},
 {id:'h6',team:'home',no:'6',nick:'ナナ',grade:'4年',height:'159cm',gender:'女',pos:'OP',x:78,y:74,zone:{w:18,h:18,r:0}}
];
const baseOpp=[['OH',22,25],['MB',50,25],['RF',78,25],['S',22,39],['L',50,39],['OP',78,39]].map((a,i)=>({id:'o'+(i+1),team:'opp',no:a[0],nick:a[0],pos:a[0],x:a[1],y:a[2],zone:{w:18,h:18,r:0}}));
function makeScene(name='サーブレシーブ'){return {id:'s'+Date.now()+Math.random().toString(16).slice(2),name,players:structuredClone([...baseHome,...baseOpp]),ball:{x:50,y:56,h:45}}}
function makeTeam(name='A'){return {id:'t'+Date.now()+Math.random().toString(16).slice(2),name,sceneId:'s1',scenes:[{...makeScene('サーブレシーブ'),id:'s1'}]}}
let state=load()||{teamId:'t1',teams:[{...makeTeam('A'),id:'t1'}]};
let selectedId='h1', dragging=null, pressTimer=null, pressStart=null, rangeMode=true;
function load(){try{return JSON.parse(localStorage.getItem(STORAGE))}catch{return null}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function team(){return state.teams.find(t=>t.id===state.teamId)||state.teams[0]}
function scene(){const t=team();return t.scenes.find(s=>s.id===t.sceneId)||t.scenes[0]}
function pctX(p){return p.x/100*court.clientWidth} function pctY(p){return p.y/100*court.clientHeight}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))} function posFromEvent(e){const r=court.getBoundingClientRect();return {x:clamp((e.clientX-r.left)/r.width*100,0,100),y:clamp((e.clientY-r.top)/r.height*100,0,100)}}
function render(){document.getElementById('sceneName').textContent=scene().name;document.getElementById('teamBtn').textContent=team().name.slice(0,2);zonesEl.innerHTML='';tokensEl.innerHTML='';scene().players.forEach(p=>{renderZone(p);renderToken(p)});renderBall();renderLists();save();}
function renderZone(p){const z=document.createElement('div');z.className=`zone ${p.team==='opp'?'opp':''} ${p.id===selectedId?'selected':''}`;z.dataset.id=p.id;const w=p.zone.w/100*court.clientWidth,h=p.zone.h/100*court.clientWidth;z.style.width=w+'px';z.style.height=h+'px';z.style.left=(pctX(p)-w/2)+'px';z.style.top=(pctY(p)-h/2)+'px';z.style.transform=`rotate(${p.zone.r||0}deg)`;zonesEl.appendChild(z);if(p.id===selectedId&&rangeMode){['e','s','se','rot'].forEach(k=>{const hnd=document.createElement('div');hnd.className='zhandle '+k;hnd.dataset.kind=k;hnd.addEventListener('pointerdown',startHandle);z.appendChild(hnd)})}}
function renderToken(p){const t=document.createElement('div');t.className=`token ${p.team==='opp'?'opp':'home'} ${p.id===selectedId?'selected':''}`;t.dataset.id=p.id;t.style.left=(pctX(p)-29)+'px';t.style.top=(pctY(p)-29)+'px';t.innerHTML=p.team==='home'?`<span class="main">${p.nick||p.no}</span><span class="sub">${p.pos||'-'}</span>`:`<span class="main">${p.pos||p.no}</span><span class="sub">${p.pos||p.no}</span>`;tokensEl.appendChild(t);t.addEventListener('pointerdown',startDrag);t.addEventListener('click',()=>{selectedId=p.id;render()});}
function renderBall(){const b=scene().ball;ballEl.style.left=(pctX(b)-23)+'px';ballEl.style.top=(pctY(b)-23-b.h/6)+'px';ballEl.style.boxShadow=`0 ${16+b.h/4}px ${12+b.h/5}px rgba(0,0,0,.28)`;ballEl.onpointerdown=e=>{e.preventDefault();dragging={type:'ball'};ballEl.setPointerCapture(e.pointerId)}}
function startDrag(e){e.preventDefault();e.stopPropagation();const id=e.currentTarget.dataset.id;selectedId=id;const p=scene().players.find(x=>x.id===id);const pos=posFromEvent(e);dragging={type:'player',id,dx:pos.x-p.x,dy:pos.y-p.y,moved:false};pressStart={x:e.clientX,y:e.clientY};pressTimer=setTimeout(()=>{pressTimer=null;if(dragging&&dragging.type==='player'&&!dragging.moved)openEdit(id)},650);e.currentTarget.setPointerCapture(e.pointerId);render();}
function startHandle(e){e.preventDefault();e.stopPropagation();const p=scene().players.find(x=>x.id===selectedId);dragging={type:'handle',kind:e.currentTarget.dataset.kind,start:{x:e.clientX,y:e.clientY,w:p.zone.w,h:p.zone.h,r:p.zone.r||0}};e.currentTarget.setPointerCapture(e.pointerId)}
window.addEventListener('pointermove',e=>{if(!dragging)return;const s=scene();if(dragging.type==='player'){const p=s.players.find(x=>x.id===dragging.id);if(Math.hypot(e.clientX-pressStart.x,e.clientY-pressStart.y)>8){dragging.moved=true;if(pressTimer){clearTimeout(pressTimer);pressTimer=null}}const pos=posFromEvent(e);p.x=clamp(pos.x-dragging.dx,3,97);p.y=clamp(pos.y-dragging.dy,3,97);render()}else if(dragging.type==='ball'){const pos=posFromEvent(e);s.ball.x=pos.x;s.ball.y=pos.y;renderBall();save()}else if(dragging.type==='handle'){const p=s.players.find(x=>x.id===selectedId);const dx=(e.clientX-dragging.start.x)/court.clientWidth*100,dy=(e.clientY-dragging.start.y)/court.clientWidth*100;if(dragging.kind==='e')p.zone.w=clamp(dragging.start.w+dx*2,10,70);if(dragging.kind==='s')p.zone.h=clamp(dragging.start.h+dy*2,10,70);if(dragging.kind==='se'){const d=Math.max(dx,dy)*2;p.zone.w=clamp(dragging.start.w+d,10,70);p.zone.h=clamp(dragging.start.h+d,10,70)}if(dragging.kind==='rot')p.zone.r=dragging.start.r+(e.clientX-dragging.start.x);render()}});
window.addEventListener('pointerup',()=>{dragging=null;if(pressTimer){clearTimeout(pressTimer);pressTimer=null}save()});
function renderLists(){const sc=document.getElementById('sceneList');sc.innerHTML='';team().scenes.forEach(s=>{const b=document.createElement('button');b.textContent=(s.id===team().sceneId?'✓ ':'')+s.name;b.onclick=()=>{team().sceneId=s.id;closeSheets();render()};b.oncontextmenu=e=>{e.preventDefault();const n=prompt('シーン名',s.name);if(n){s.name=n;render()}};sc.appendChild(b)});const pl=document.getElementById('playerList');pl.innerHTML='';scene().players.filter(p=>p.team==='home').forEach(p=>{const row=document.createElement('div');row.className='player-row';row.innerHTML=`<div class="badge">${p.no||''}</div><div class="meta"><div class="name">${p.nick}</div><div class="detail">${p.pos||'-'} / ${p.grade||'-'} / ${p.height||'-'}</div></div><span>›</span>`;row.onclick=()=>openEdit(p.id);pl.appendChild(row)});const tl=document.getElementById('teamList');tl.innerHTML='';state.teams.forEach(t=>{const b=document.createElement('button');b.textContent=(t.id===state.teamId?'✓ ':'')+t.name+'チーム';b.onclick=()=>{state.teamId=t.id;closeSheets();render()};b.oncontextmenu=e=>{e.preventDefault();const n=prompt('チーム名',t.name);if(n){t.name=n;render()}};tl.appendChild(b)})}
function openSheet(id){document.getElementById(id).classList.add('open')}function closeSheets(){document.querySelectorAll('.sheet').forEach(s=>s.classList.remove('open'))}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).classList.remove('open'));
document.getElementById('sceneBtn').onclick=()=>openSheet('sceneSheet');document.getElementById('playersBtn').onclick=()=>openSheet('playerSheet');document.getElementById('teamBtn').onclick=()=>openSheet('teamSheet');document.getElementById('teamHandle').onclick=()=>openSheet('teamSheet');document.getElementById('playerHandle').onclick=()=>openSheet('playerSheet');
document.getElementById('newSceneBtn').onclick=()=>{const name=prompt('シーン名','新しいシーン');if(!name)return;const base=structuredClone(scene());base.id='s'+Date.now();base.name=name;team().scenes.push(base);team().sceneId=base.id;render()};document.getElementById('sceneAddBtn').onclick=()=>document.getElementById('newSceneBtn').click();
document.getElementById('addTeamBtn').onclick=()=>{const name=prompt('チーム名','B');if(!name)return;const nt=makeTeam(name);state.teams.push(nt);state.teamId=nt.id;closeSheets();render()};
document.getElementById('addPlayerBtn').onclick=()=>{const no=String(scene().players.filter(p=>p.team==='home').length+1);const p={id:'h'+Date.now(),team:'home',no,nick:'新規',grade:'',height:'',gender:'未設定',pos:'',x:50,y:82,zone:{w:18,h:18,r:0}};scene().players.push(p);selectedId=p.id;closeSheets();render();setTimeout(()=>openEdit(p.id),100)};
document.getElementById('resetBtn').onclick=()=>{if(confirm('このシーンを初期配置に戻しますか？')){scene().players=structuredClone([...baseHome,...baseOpp]);scene().ball={x:50,y:56,h:45};render()}};
document.getElementById('rangeBtn').onclick=()=>{rangeMode=!rangeMode;render()};document.getElementById('ballBtn').onclick=()=>{scene().ball={x:50,y:56,h:45};render()};document.getElementById('undoBtn').onclick=()=>alert('UNDOは次回実装予定です');
function openEdit(id){selectedId=id;const p=scene().players.find(x=>x.id===id);if(!p)return;document.getElementById('editTitle').textContent=p.team==='opp'?'相手選手編集':'選手編集';document.getElementById('editNick').value=p.nick||'';document.getElementById('editNo').value=p.no||'';document.getElementById('editGrade').value=p.grade||'';document.getElementById('editHeight').value=p.height||'';document.getElementById('editGender').value=p.gender||'未設定';document.getElementById('editPos').value=p.pos||'';document.getElementById('editPersonality').value=p.personality||'';document.getElementById('editCoach').value=p.coach||'';document.getElementById('editBackdrop').classList.add('open');document.getElementById('editSheet').classList.add('open');render()}
function closeEdit(){document.getElementById('editBackdrop').classList.remove('open');document.getElementById('editSheet').classList.remove('open')}document.getElementById('cancelEdit').onclick=closeEdit;document.getElementById('editBackdrop').onclick=closeEdit;document.getElementById('saveEdit').onclick=()=>{const p=scene().players.find(x=>x.id===selectedId);p.nick=document.getElementById('editNick').value;p.no=document.getElementById('editNo').value;p.grade=document.getElementById('editGrade').value;p.height=document.getElementById('editHeight').value;p.gender=document.getElementById('editGender').value;p.pos=document.getElementById('editPos').value;p.personality=document.getElementById('editPersonality').value;p.coach=document.getElementById('editCoach').value;closeEdit();render()};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('publicTab').classList.toggle('hidden',b.dataset.tab!=='public');document.getElementById('coachTab').classList.toggle('hidden',b.dataset.tab!=='coach')});
let sx=0,sy=0;window.addEventListener('touchstart',e=>{sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});window.addEventListener('touchend',e=>{if(dragging)return;const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;const edge=44;const strongHorizontal=Math.abs(dx)>120&&Math.abs(dx)>Math.abs(dy)*2.3;if(strongHorizontal){if(sx>window.innerWidth-edge&&dx<0)openSheet('playerSheet');if(sx<edge&&dx>0)openSheet('teamSheet')}if(sy<54&&dy>140&&Math.abs(dx)<70)openSheet('sceneSheet')},{passive:true});
render();
